ganglia:
    image: adolphlwq/ganglia
    privileged: true
    ipc: host
    net: host
    pid: host
    container_name: ganglia
    volumes:
        - /sys:/sys
        - /dev:/dev
        - ./ganglia:/etc/ganglia
